# -------- Builder Stage --------
FROM python:3.11-alpine AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# -------- Runtime Stage --------
FROM python:3.11-alpine

WORKDIR /app

COPY --from=builder /install /usr/local

COPY src ./src

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]