---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: observability
data:
  environment: "production"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-sdk-config
  namespace: default
data:
  OTEL_SDK_DISABLED: "false"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_TIMEOUT: "10000"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318/v1/metrics"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318/v1/logs"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=food-delivery,service.version=${APP_VERSION}"
  OTEL_TRACE_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACE_SAMPLER_ARG: "0.1"
