apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: food-delivery

resources:
  - core-services.yaml
  - additional-services.yaml
  - api-gateway.yaml
  - hpa.yaml
  - pdb.yaml
